name: Test

on: ['push']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: scripts/verify-push.sh
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
